name = "JuliaProjectFormatter"
uuid = "139e0cf6-64b2-48ae-acd2-4285c0bb47c3"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1.6"
